bank_app/urls.py
from django.urls import path
from . import views

app_name = 'bank_app'

urlpatterns = [
        path('', views.index, name='index'),
        path('frontpage_customer/', views.frontpage_customer, name='frontpage_customer'),
        path('account_details/<int:pk>/', views.account_details, name='account_details'),
        path('transaction_details/<int:transaction>/', views.transaction_details, name='transaction_details'),
        path('transfer_options/', views.transfer_options, name='transfer_options'),
        path('make_transfer/', views.make_transfer, name='make_transfer'),
        path('make_external_transfer/', views.make_external_transfer, name='make_external_transfer'),
        path('apply_loan/', views.apply_loan, name='apply_loan'),

        path('frontpage_staff/', views.frontpage_staff, name='frontpage_staff'),
        path('staff_search_partial/', views.staff_search_partial, name='staff_search_partial'),
        path('staff_customer_details/<int:pk>/', views.staff_customer_details, name='staff_customer_details'),
        path('staff_account_list_partial/<int:pk>/', views.staff_account_list_partial, name='staff_account_list_partial'),
        path('staff_account_details/<int:pk>/', views.staff_account_details, name='staff_account_details'),
        path('staff_new_account_partial/<int:user>/', views.staff_new_account_partial, name='staff_new_account_partial'),
        path('staff_new_customer/', views.staff_new_customer, name='staff_new_customer'),
        path('staff_loan_applications/', views.staff_loan_applications, name='staff_loan_applications'),
        path('staff_approve_loan/<int:pk>/<slug:user>', views.staff_approve_loan, name='staff_approve_loan'),
        path('staff_deny_loan/<int:pk>/<slug:user>', views.staff_deny_loan, name='staff_deny_loan'),

        path('logout/', views.logout, name='logout'),
]

bank_project/urls.py
from django.contrib import admin
from django.urls import path, include
from two_factor.urls import urlpatterns as tf_urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(tf_urls)),
    path('', include('bank_app.urls')),
    path('external_transfer/', include('transfer_api.urls'))
]

bank_app/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from .models import Customer, Account


class TransferForm(forms.Form):
    amount  = forms.DecimalField(label='Amount', max_digits=10)
    debit_account = forms.ModelChoiceField(label='Debit Account', queryset=Customer.objects.none())
    debit_text = forms.CharField(label='Debit Account Text', max_length=25)
    credit_account = forms.IntegerField(label='Credit Account Number')
    credit_text = forms.CharField(label='Credit Account Text', max_length=25)

    def clean(self):
        super().clean()

        # Ensure credit account exist
        credit_account = self.cleaned_data.get('credit_account')
        try:
            Account.objects.get(pk=credit_account)
        except ObjectDoesNotExist:
            self._errors['credit_account'] = self.error_class(['Credit account does not exist.'])

        # Ensure positive amount
        if self.cleaned_data.get('amount') < 0:
            self._errors['amount'] = self.error_class(['Amount must be positive.'])

        return self.cleaned_data


class NewUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')

    def clean(self):
        super().clean()
        username = self.cleaned_data.get('username')
        if User.objects.filter(username=username):
            self._errors['username'] = self.error_class(['Username already exists.'])
        return self.cleaned_data


class UserForm(forms.ModelForm):
    username = forms.CharField(label='Username', disabled=True)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')


class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ('rank', 'personal_id', 'phone')


class NewAccountForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ('name',)

bank_app/views.py
from decimal import Decimal
from secrets import token_urlsafe
from django.http import HttpResponseRedirect
from django.shortcuts import render, reverse, get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.db import IntegrityError, transaction
from .forms import TransferForm, UserForm, CustomerForm, NewUserForm, NewAccountForm
from .models import Account, Ledger, Customer, LoanApplications, UID
from .errors import InsufficientFunds
import requests
from django.contrib.auth import logout as dj_logout


@login_required
def index(request):
    if request.user.is_verified():
        if request.user.is_staff:
            return HttpResponseRedirect(reverse('bank_app:frontpage_staff'))
        else:
            return HttpResponseRedirect(reverse('bank_app:frontpage_customer'))
    else:
        if request.user.is_staff:
            return HttpResponseRedirect(reverse('bank_app:frontpage_staff'))
        else:
            context = {}
            return render(request, 'two_factor/core/otp_required.html', context)


# Customer views

@login_required
def frontpage_customer(request):
    assert not request.user.is_staff, 'Staff user routing customer view.'

    accounts = request.user.customer.accounts
    context = {
        'accounts': accounts,
    }
    return render(request, 'bank_app/frontpage_customer.html', context)


@login_required
def account_details(request, pk):
    assert not request.user.is_staff, 'Staff user routing customer view.'

    account = get_object_or_404(Account, user=request.user, pk=pk)
    context = {
        'account': account,
    }
    return render(request, 'bank_app/account_details.html', context)


@login_required
def transaction_details(request, transaction):
    movements = Ledger.objects.filter(transaction=transaction)
    if not request.user.is_staff:
        if not movements.filter(account__in=request.user.customer.accounts):
            raise PermissionDenied('Customer is not part of the transaction.')
    context = {
        'movements': movements,
    }
    return render(request, 'bank_app/transaction_details.html', context)

@login_required
def transfer_options(request):
    context = {}
    return render(request, 'bank_app/transfer_options.html', context)

@login_required
def make_transfer(request):
    assert not request.user.is_staff, 'Staff user routing customer view.'

    if request.method == 'POST':
        form = TransferForm(request.POST)
        form.fields['debit_account'].queryset = request.user.customer.accounts
        if form.is_valid():
            amount = form.cleaned_data['amount']
            debit_account = Account.objects.get(pk=form.cleaned_data['debit_account'].pk)
            debit_text = form.cleaned_data['debit_text']
            credit_account = Account.objects.get(pk=form.cleaned_data['credit_account'])
            credit_text = form.cleaned_data['credit_text']
            try:
                transfer = Ledger.transfer(amount, debit_account, debit_text, credit_account, credit_text)
                return transaction_details(request, transfer)
            except InsufficientFunds:
                context = {
                    'title': 'Transfer Error',
                    'error': 'Insufficient funds for transfer.'
                }
                return render(request, 'bank_app/error.html', context)
    else:
        form = TransferForm()
    form.fields['debit_account'].queryset = request.user.customer.accounts
    context = {
        'form': form,
    }
    return render(request, 'bank_app/make_transfer.html', context)

@login_required
def make_external_transfer(request):
    if request.method == 'POST':
        amount = int(request.POST['amount'])
        credit_account = int(request.POST['credit_account'])
        debit_account = request.POST['debit_account']
        credit_text = request.POST['credit_text']
        debit_text = request.POST['debit_text']
        transfer_url = 'http://127.0.0.1:4000/external_transfer/transfer'
        id_data = {'id': credit_account}
        post_response = requests.post(transfer_url, data=id_data)
        if post_response.status_code == 200:
            transaction_id = UID.uid
            put_url = f'http://127.0.0.1:4000/external_transfer/confirm_transfer/{transaction_id}'
            put_data = {"amount": amount, "credit_account": credit_account, "credit_text": credit_text}
            put_response = requests.put(put_url, data=put_data)
            if put_response.status_code == 200:
                try:
                    d_account = get_object_or_404(Account, id=debit_account)
                    transfer = Ledger.objects.create(amount=-amount, transaction=transaction_id, account=d_account, text=debit_text)
                    return transaction_details(request, transaction_id)
                except InsufficientFunds:
                    delete_url = 'http://127.0.0.1:4000/external_transfer/rollback'
                    delete_response = requests.delete(delete_url, data={'id': transaction_id})
                    self.assertEquals(delete_response.status_code, 200)
                    context = {
                        'title': 'Transfer Error',
                        'error': 'Insufficient funds for transfer.'
                    }
                    return render(request, 'bank_app/error.html', context)
            else:
                context = {
                    'title': 'Transfer Error',
                    'error': f'Something went wrong.. error: {put_response.status_code}'
                }
                return render(request, 'bank_app/error.html', context)
        else:
            context = {
                'title': 'Transfer Error',
                'error': f'Something went wrong.. error: {post_response.status_code}'
            }
            return render(request, 'bank_app/error.html', context)
    
    form = TransferForm()
    form.fields['debit_account'].queryset = request.user.customer.accounts
    context = {
        'form': form,
    }
    return render(request, 'bank_app/make_external_transfer.html', context)

@login_required
def apply_loan(request):
    assert not request.user.is_staff, 'Staff user routing customer view.'

    if not request.user.customer.can_make_loan:
        context = {
            'title': 'Apply Loan Error',
            'error': 'Only Gold members can apply for loans.'
        }
        return render(request, 'bank_app/error.html', context)

    if request.method == 'POST':
        user = request.user
        name = request.POST['name']
        amount = Decimal(request.POST['amount'])
        loan_desc = request.POST['loan_desc']
        try:
            LoanApplications.objects.create(user=user, name=name, amount=amount, loan_desc=loan_desc)
            return HttpResponseRedirect(reverse('bank_app:frontpage_customer'))
        except ServerFail:
                context = {
                    'title': 'Loan Application Error',
                    'error': 'Server error'
                }
                return render(request, 'bank_app/error.html', context)
        
    return render(request, 'bank_app/apply_loan.html', context={})

# Staff views

@login_required
def frontpage_staff(request):
    assert request.user.is_staff, 'Customer user routing staff view.'

    return render(request, 'bank_app/frontpage_staff.html')


@login_required
def staff_search_partial(request):
    assert request.user.is_staff, 'Customer user routing staff view.'

    search_term = request.POST['search_term']
    customers = Customer.search(search_term)
    context = {
        'customers': customers,
    }
    return render(request, 'bank_app/staff_search_partial.html', context)


@login_required
def staff_customer_details(request, pk):
    assert request.user.is_staff, 'Customer user routing staff view.'

    customer = get_object_or_404(Customer, pk=pk)
    if request.method == 'GET':
        user_form = UserForm(instance=customer.user)
        customer_form = CustomerForm(instance=customer)
    elif request.method == 'POST':
        user_form = UserForm(request.POST, instance=customer.user)
        customer_form = CustomerForm(request.POST, instance=customer)
        if user_form.is_valid() and customer_form.is_valid():
            user_form.save()
            customer_form.save()
    new_account_form = NewAccountForm()
    context = {
        'customer': customer,
        'user_form': user_form,
        'customer_form': customer_form,
        'new_account_form': new_account_form,
    }
    return render(request, 'bank_app/staff_customer_details.html', context)


@login_required
def staff_account_list_partial(request, pk):
    assert request.user.is_staff, 'Customer user routing staff view.'

    customer = get_object_or_404(Customer, pk=pk)
    accounts = customer.accounts
    context = {
        'accounts': accounts,
    }
    return render(request, 'bank_app/staff_account_list_partial.html', context)


@login_required
def staff_account_details(request, pk):
    assert request.user.is_staff, 'Customer user routing staff view.'

    account = get_object_or_404(Account, pk=pk)
    context = {
        'account': account,
    }
    return render(request, 'bank_app/account_details.html', context)


@login_required
def staff_new_account_partial(request, user):
    assert request.user.is_staff, 'Customer user routing staff view.'

    if request.method == 'POST':
        new_account_form = NewAccountForm(request.POST)
        if new_account_form.is_valid():
            Account.objects.create(user=User.objects.get(pk=user), name=new_account_form.cleaned_data['name'])
    return HttpResponseRedirect(reverse('bank_app:staff_customer_details', args=(user,)))


@login_required
def staff_new_customer(request):
    assert request.user.is_staff, 'Customer user routing staff view.'

    if request.method == 'POST':

bank_app/templates/bank_app/account_details.html
{% extends "base.html" %}

{% block main %}

{% if user.is_staff %}
<p>Welcome, {{ user }}.</p>
{% else %}
<p>Welcome, {{ user.customer.full_name }}.</p>
{% endif %}

<h3>Account Details</h3>

<table>
	<tr>
		<th>Account Number</th>
		<th>Account Name</th>
		<th>Balance</th>
	</tr>
	<tr>
		<td>{{ account.pk }}</td>
		<td>{{ account.name }}</td>
		<td class="amount">{{ account.balance|floatformat:"2" }}</td>
	</tr>
</table>

<h3>Account Transactions</h3>

<table>
    <tr>
        <th>Transaction UID</th>
        <th>Amount</th>
        <th>Date and Time</th>
        <th>Text</th>
    </tr>
    {% for movement in account.movements %}
    <tr>
        <td><a href="{% url 'bank_app:transaction_details' movement.transaction %}">{{ movement.transaction }}</a></td>
        <td>{{ movement.amount|floatformat:"2" }}</td>
        <td>{{ movement.timestamp }}</td>
        <td>{{ movement.text }}</td>
    </tr>
    {% endfor %}
</table>

{% endblock main %}

bank_app/templates/bank_app/apply_loan.html
{% extends "base.html" %}

{% block main %}
<h1>Apply for loan</h1>
<p>Fill out the form to apply for a loan</p>
<form action="{% url 'bank_app:apply_loan' %}" method="post">
    {% csrf_token %}
    <fieldset>
    <label for="name">Name for loan</label>
    <input name="name" type="text" />
    
    <label for="amount">Amount</label>
    <input name="amount" type="number" />

    <label for="loan_desc">Description</label>
    <input name="loan_desc" type="text"/>
    
    <button>Submit</button>
    </fieldset>
</form>
{% endblock main %}

bank_app/templates/bank_app/error.html
{% extends "base.html" %}

{% block main %}

<p>Welcome, {% if user.is_staff %}{{ user.username }}{% else %}{{ user.customer.full_name }}{% endif %}.</p>

<h3>{{ title }}</h3>

<p>{{ error }}</p>

{% endblock main %}

bank_app/templates/bank_app/frontpage_customer.html
{% extends "base.html" %}

{% block main %}

<p>Welcome, {{ user.customer.full_name }}.</p>

<h3>My accounts:</h3>
<table>
    <tr>
        <th>Account Number</th>
        <th>Account Name</th>
    </tr>
    {% for account in accounts %}
    <tr>
        <td><a href="{% url 'bank_app:account_details' account.pk %}">{{ account.pk }}</a></td>
        <td>{{ account.name }}</td>
    </tr>
    {% endfor %}
</table>
{% endblock main %}

bank_app/templates/bank_app/frontpage_staff.html
{% extends "base.html" %}

{% block main %}

<h1>Welcome, {{ user }}.</h1>

<fieldset>
    <label>Customer Look Up</label>
    <input name="search_term"
           placeholder="Search on customer data"
           class="form-control"
           type="text"
           hx-post="{% url 'bank_app:staff_search_partial' %}"
           hx-trigger="keyup changed delay:500ms"
           hx-target="#search-results"
           hx-indicator=".htmx-indicator"
    />
    {% csrf_token %}
</fieldset>

<table>
    <thead>
        <th>ID</th>
        <th>Persal ID</th>
        <th>Name</th>
        <th>Phone</th>
        <th>Email</th>
    </thead>
    <tbody id="search-results">
    </tbody>
</table>

{% endblock main %}

bank_app/templates/bank_app/make_external_transfer.html
{% extends "base.html" %}

{% block main %}
<h1>Make external transfer</h1>
<form action="{% url 'bank_app:make_external_transfer' %}" method="post">
    {% csrf_token %}
    <fieldset>
        {{ form }}
    <button>Transfer</button>
    </fieldset>
</form>
<a href="../make_transfer">Make internal transfer</a>
{% endblock main %}

bank_app/templates/bank_app/make_transfer.html
{% extends "base.html" %}

{% block main %}
<h1>Make internal transfer</h1>
<form action="{% url 'bank_app:make_transfer' %}" method="post">
    {% csrf_token %}
    <fieldset>
        {{ form }}
    <button>Transfer</button>
    </fieldset>
</form>
<a href="../make_external_transfer">Make external transfer</a>
{% endblock main %}

bank_app/templates/bank_app/staff_account_list_partial.html
<tbody id="account-list">
    {% for account in accounts %}
        <tr>
            <td><a href="{% url 'bank_app:staff_account_details' account.pk %}">{{ account.pk }}</a></td>
            <td>{{ account.name }}</td>
            <td>{{ account.balance|floatformat:"2" }}</td>
        </tr>
    {% endfor %}
</tbody>

bank_app/templates/bank_app/staff_customer_details.html
{% extends "base.html" %}

{% block main %}

<h3>Customer Details</h3>

<form action="{% url 'bank_app:staff_customer_details' customer.pk %}" method="post">
    {% csrf_token %}
    <fieldset>
        {{ user_form.as_p }}
        {{ customer_form.as_p }}
    <button>Update User</button>
    </fieldset>
</form>

<table>
    <thead>
        <tr>
            <th>Account Number</th>
            <th>Account Name</th>
            <th>Account Balance</th>
        </tr>
    </thead>
    <tbody
        id="account-list"
        hx-swap="outerHTML"
        hx-get="{% url 'bank_app:staff_account_list_partial' customer.pk %}"
        hx-trigger="load">
    </tbody>
</table>

<h3>Create New Account</h3>
<form action="{% url 'bank_app:staff_new_account_partial' customer.user.pk %}" method="post">
    {% csrf_token %}
    <fieldset>
        {{ new_account_form.as_p }}
    <button>Create Account</button>
    </fieldset>
</form>

{% endblock main %}

bank_app/templates/bank_app/staff_loan_applications.html
{% extends "base.html" %}

{% block main %}

<h1>Loan Applications</h1>
<table>
    <tr>
        <th>User</th>
        <th>Name</th>
        <th>Amount</th>
        <th>Description</th>
        <th>Approve</th>
        <th>Deny</th>
    </tr>
    {% for application in loan_applications %}     
    <tr>
        <td>{{ application.user }}</td>
        <td>{{ application.name }}</td>
        <td>{{ application.amount }}</td>
        <td>{{ application.loan_desc }}</td>
        <td>
            <form class="button_form" action="{% url 'bank_app:staff_approve_loan' application.pk application.user %}" method="post">
                {% csrf_token %}
                <input name="amount" value="{{ application.amount }}" type="hidden">
                <input name="name" value="{{ application.name }}" type="hidden">
                <button>Approve</button>
            </form>
        </td>
        <td>
            <form class="button_form" action="{% url 'bank_app:staff_deny_loan' application.pk application.user %}" method="post">
                {% csrf_token %}
                <button>Deny</button>
            </form>
        </td>
    </tr>
    {% endfor %}
</table>

{% endblock main %}

bank_app/templates/bank_app/staff_new_customer.html
{% extends "base.html" %}

{% block main %}
<h1>Create new customer</h1>
<form action="{% url 'bank_app:staff_new_customer' %}" method="post">
    {% csrf_token %}
    <fieldset>
        {{ new_user_form }}
        {{ customer_form }}
    <button>Create User</button>
    </fieldset>
</form>
{% endblock main %}

bank_app/templates/bank_app/staff_search_partial.html
{% for customer in customers %}
<tr>
    <td><a href="{% url 'bank_app:staff_customer_details' customer.pk %}">{{ customer.pk }}</a></td>
    <td>{{ customer.personal_id }}</td>
    <td>{{ customer.full_name }}</td>
    <td>{{ customer.phone }}</td>
    <td>{{ customer.user.email }}</td>
</tr>
{% endfor %}

bank_app/templates/bank_app/transaction_details.html
{% extends "base.html" %}

{% block main %}

<p>Welcome, {{ user.customer.full_name }}.</p>

<h3>Transaction Details</h3>

<table>
    <tr>
        <th>Account Number</th>
        <th>Transaction UID</th>
        <th>Amount</th>
        <th>Date and Time</th>
        <th>Text</th>
    </tr>
    {% for movement in movements %}
    <tr>
        <td>{{ movement.account }}</td>
        <td>{{ movement.transaction }}</td>
        <td>{{ movement.amount|floatformat:"2" }}</td>
        <td>{{ movement.timestamp }}</td>
        <td>{{ movement.text }}</td>
    </tr>
    {% endfor %}
</table>

{% endblock main %}

bank_app/templates/bank_app/transfer_options.html
{% extends "base.html" %}

{% block main %}
<div id="transfer_options">
    <a href="../make_transfer"><button>Make internal transfer</button></a>
    <a href="../make_external_transfer"><button>Make external transfer</button></a> 
</div>
{% endblock main %}